  "draw": {
    "topology": "triangles",
    "vertex_count": 3,
    "fullscreen_triangle": true
  },
  "fixed_function": {
    "samples": 1,
    "blend": false,
    "depth_test": false,
    "depth_write": false,
    "stencil_test": false,
    "cull": false,
    "scissor": false,
    "dither": false,
    "logic_op": "copy",
    "color_write_mask": "rgba"
  },
  "attributes": [
    {
      "name": "a_pos",
      "location": 0,
      "components": 2,
      "type": "float32"
    },
    {
      "name": "a_texcoord",
      "location": 1,
      "components": 2,
      "type": "float32"
    }
  ],
